/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pt_task2252026_beldad;

import java.sql.Date;
import java.sql.SQLException;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beldad
 */
public class UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UI.class.getName());
    private final AttendanceService attendanceService = new AttendanceService();

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        initializeFormState();
        loadAttendanceRecords(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        studentIDTXT = new javax.swing.JTextField();
        dateSpinner1 = new javax.swing.JSpinner();
        statusComboBox = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateSpinner2 = new javax.swing.JSpinner();
        filterDateBtn = new javax.swing.JButton();
        showAllBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AttendanceTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Attendance Monitoring");

        nameTXT.setText("nametxt");

        studentIDTXT.setText("studentIDtxt");

        dateSpinner1.setModel(new javax.swing.SpinnerDateModel());
        dateSpinner1.setMaximumSize(null);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Present", "Absent", "Late", "Excuse", "Cutting" }));

        addBtn.setText("ADD");
        addBtn.addActionListener(this::addBtnActionPerformed);

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(this::clearBtnActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NAME:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("STUDENT ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("DATE:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("STATUS:");

        dateSpinner2.setModel(new javax.swing.SpinnerDateModel());
        dateSpinner2.setToolTipText("");

        filterDateBtn.setText("FILTER BY DATE");
        filterDateBtn.addActionListener(this::filterDateBtnActionPerformed);

        showAllBtn.setText("SHOW ALL");
        showAllBtn.addActionListener(this::showAllBtnActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("FILTER DATE:");

        AttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AttendanceTable);
        if (AttendanceTable.getColumnModel().getColumnCount() > 0) {
            AttendanceTable.getColumnModel().getColumn(0).setResizable(false);
            AttendanceTable.getColumnModel().getColumn(1).setResizable(false);
            AttendanceTable.getColumnModel().getColumn(2).setResizable(false);
            AttendanceTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Attendance Record");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showAllBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filterDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateSpinner2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateBtn))
                            .addComponent(nameTXT)
                            .addComponent(studentIDTXT)
                            .addComponent(dateSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(updateBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBtn)
                            .addComponent(clearBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterDateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showAllBtn)
                        .addContainerGap(255, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String studentId = studentIDTXT.getText().trim();
        String name = nameTXT.getText().trim();
        String status = (String) statusComboBox.getSelectedItem();
        Date attendanceDate = getDateFromSpinner(dateSpinner1);

        if (studentId.isEmpty() || name.isEmpty() || status == null) {
            JOptionPane.showMessageDialog(this, "Student ID, Name, Date, and Status are required.");
            return;
        }

        try {
            if (attendanceService.attendanceExists(studentId, attendanceDate)) {
                JOptionPane.showMessageDialog(this, "Duplicate attendance: this student already has a record for that date.");
                return;
            }

            attendanceService.addAttendance(studentId, name, attendanceDate, status);
            JOptionPane.showMessageDialog(this, "Attendance record added.");
            loadAttendanceRecords(null);
            clearForm();
        } catch (SQLException ex) {
            if (Objects.equals(ex.getSQLState(), "23505")) {
                JOptionPane.showMessageDialog(this, "Duplicate attendance: this student already has a record for that date.");
            } else {
                showDatabaseError("Unable to add attendance.", ex);
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String studentId = studentIDTXT.getText().trim();
        String name = nameTXT.getText().trim();
        String status = (String) statusComboBox.getSelectedItem();
        Date attendanceDate = getDateFromSpinner(dateSpinner1);

        if (studentId.isEmpty() || name.isEmpty() || status == null) {
            JOptionPane.showMessageDialog(this, "Select a row first or fill all fields.");
            return;
        }

        try {
            int updatedRows = attendanceService.updateAttendance(studentId, name, attendanceDate, status);
            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(this, "Attendance record updated.");
                loadAttendanceRecords(null);
            } else {
                JOptionPane.showMessageDialog(this, "No matching record found to update.");
            }
        } catch (SQLException ex) {
            showDatabaseError("Unable to update attendance.", ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String studentId = studentIDTXT.getText().trim();
        Date attendanceDate = getDateFromSpinner(dateSpinner1);

        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student ID is required to delete.");
            return;
        }

        try {
            int deletedRows = attendanceService.deleteAttendance(studentId, attendanceDate);
            if (deletedRows > 0) {
                JOptionPane.showMessageDialog(this, "Attendance record deleted.");
                loadAttendanceRecords(null);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "No matching record found to delete.");
            }
        } catch (SQLException ex) {
            showDatabaseError("Unable to delete attendance.", ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearForm();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void filterDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDateBtnActionPerformed
        Date filterDate = getDateFromSpinner(dateSpinner2);
        loadAttendanceRecords(filterDate);
    }//GEN-LAST:event_filterDateBtnActionPerformed

    private void showAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtnActionPerformed
        loadAttendanceRecords(null);
    }//GEN-LAST:event_showAllBtnActionPerformed

    private void initializeFormState() {
        dateSpinner1.setEditor(new JSpinner.DateEditor(dateSpinner1, "yyyy-MM-dd"));
        dateSpinner2.setEditor(new JSpinner.DateEditor(dateSpinner2, "yyyy-MM-dd"));
        statusComboBox.setModel(new DefaultComboBoxModel<>(new String[]{"Present", "Absent"}));

        AttendanceTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                fillFormFromSelectedRow();
            }
        });

        clearForm();
    }

    private void loadAttendanceRecords(Date filterDate) {
        try {
            DefaultTableModel model = (DefaultTableModel) AttendanceTable.getModel();
            model.setRowCount(0);

            for (Object[] row : attendanceService.getAttendanceRecords(filterDate)) {
                model.addRow(row);
            }
        } catch (SQLException ex) {
            showDatabaseError("Unable to load attendance records.", ex);
        }
    }

    private void fillFormFromSelectedRow() {
        int selectedRow = AttendanceTable.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) AttendanceTable.getModel();
        studentIDTXT.setText(String.valueOf(model.getValueAt(selectedRow, 0)));
        nameTXT.setText(String.valueOf(model.getValueAt(selectedRow, 1)));
        statusComboBox.setSelectedItem(String.valueOf(model.getValueAt(selectedRow, 3)));

        Object dateValue = model.getValueAt(selectedRow, 2);
        if (dateValue instanceof Date) {
            Date selectedDate = (Date) dateValue;
            dateSpinner1.setValue(new java.util.Date(selectedDate.getTime()));
        } else if (dateValue != null) {
            try {
                Date parsedDate = Date.valueOf(dateValue.toString());
                dateSpinner1.setValue(new java.util.Date(parsedDate.getTime()));
            } catch (IllegalArgumentException ex) {
                // Ignore invalid date text from table cell.
            }
        }
    }

    private Date getDateFromSpinner(JSpinner spinner) {
        java.util.Date utilDate = (java.util.Date) spinner.getValue();
        return new Date(utilDate.getTime());
    }

    private void clearForm() {
        studentIDTXT.setText("");
        nameTXT.setText("");
        statusComboBox.setSelectedIndex(0);
        dateSpinner1.setValue(new java.util.Date());
        AttendanceTable.clearSelection();
    }

    private void showDatabaseError(String message, SQLException ex) {
        JOptionPane.showMessageDialog(
                this,
                message + "\n" + ex.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttendanceTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JSpinner dateSpinner1;
    private javax.swing.JSpinner dateSpinner2;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton filterDateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JButton showAllBtn;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField studentIDTXT;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
